CREATE DATABASE AKNES;
USE AKNES;
CREATE TABLE STUDENT( STUDENT_NAME INT PRIMARY KEY,STUDENT_ID VARCHAR(50),DEPT_IT VARCHAR(50));
UPDATE STUDENT
SET DEPARTMENT =103
WHERE STUDENT_NAME='KARTHIC';
DELETE FROM STUDENT
WHERE STUDENT_ID=1002;
SELECT*FROM STUDENT;
